repos:
  # === Syntax & Basic Checks ===
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
        name: Validate Python syntax
      - id: check-yaml
        name: Validate YAML files
      - id: check-json
        name: Validate JSON files
      - id: check-toml
        name: Validate TOML files
      - id: mixed-line-ending
        name: Normalize line endings
        args: ['--fix=lf']
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure file ends with newline

  # === Security ===
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        name: Check for private keys
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: debug-statements
        name: Check for debugger imports

  # === Type Checking ===
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.387
    hooks:
      - id: pyright
        name: Run Pyright type checker
        args: ["--level", "error"]
        types_or: [python, pyi, jupyter]
        files: ^(src|tests)/
        exclude: ^src/experimental/
        verbose: true
        fail_fast: false

  # === Code Quality & Style ===
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        name: Run Ruff linter
        args: [
          --fix,
          --exit-zero,
        ]
        types_or: [python, pyi, jupyter]
        files: ^(src|tests)/
        exclude: ^src/experimental/
      - id: ruff-format
        name: Run Ruff formatter
        types_or: [python, pyi, jupyter]

  # === Testing & Documentation ===
  - repo: local
    hooks:
      - id: pytest-check
        name: Run pytest suite
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        args: [
          "--quiet",
          "--no-header",
          "--cov=src",
          "--cov-report=term-missing:skip-covered",
          "-ra",
          "--run-integration",
        ]
        verbose: true

      - id: update-project-structure
        name: Update project documentation
        entry: python scripts/generate_structure.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
