# Pre-commit configuration for Python project quality checks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        description: 'Removes trailing whitespace from all files'
    -   id: check-yaml
        description: 'Validates YAML syntax'
    -   id: check-ast
        description: 'Validates Python syntax'
    -   id: check-json
        description: 'Validates JSON syntax'
    -   id: check-merge-conflict
        description: 'Checks for merge conflict markers'
    -   id: detect-private-key
        description: 'Prevents committing private keys'
    -   id: end-of-file-fixer
        description: 'Ensures files end with a newline'
    -   id: mixed-line-ending
        description: 'Normalizes line endings'
        args: ['--fix=lf']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
    -   id: ruff
        description: 'Run Ruff linter with auto-fixes'
        args: [--fix]
        types_or: [python, pyi, jupyter]
    -   id: ruff-format
        description: 'Run Ruff formatter'
        types_or: [python, pyi, jupyter]

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        description: 'Run pytest suite'
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        # Add verbose output and show test coverage
        args: ["-v", "--cov=src", "--cov-report=term-missing"]

    -   id: update-project-structure
        name: update project structure
        description: 'Updates project structure documentation'
        entry: python scripts/generate_structure.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
