[variables]
NIXPACKS_PYTHON_VERSION = "3.12.9"
NIXPACKS_UV_VERSION = "0.6.0"
UV_LINK_MODE = "copy"

[phases.setup]
# Specifies the required Python version
nixpkgs = ["python312", "gcc", "glibc",]

[phases.install]
# Set up a virtual environment and install dependencies
# Cache dependencies layer
cache_directories = [
    "/root/.cache/uv"  # UV's cache for packages
]
cmds = [
  "echo '🚀 Starting Kollektiv installation...'",
  # Download installer
  # "curl -LsSf https://astral.sh/uv/${NIXPACKS_UV_VERSION}/install.sh -o /uv-installer.sh",
  # Download and install UV
  "curl -LsSf https://astral.sh/uv/${NIXPACKS_UV_VERSION}/install.sh | sh",
  ". /root/.local/bin/env",
  # Install UV
  # "sh /uv-installer.sh && rm /uv-installer.sh",
  # Sync dependencies without updating
  "uv sync --frozen --no-dev",
  "echo \"🚀 Starting Kollektiv service: ${SERVICE}\"",
]

[start]
cmd = "kollektiv $SERVICE"
