name: kollektiv-local-deps
services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  rq-worker:
    build:
      context: ../../
      dockerfile: scripts/docker/Dockerfile
    deploy:
      replicas: 2
    env_file:
      - ../../config/environments/.env
    volumes:
      - ../../:/app
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_QUEUE_NAME=${REDIS_QUEUE_NAME:-process_documents_queue}
      - CHROMA_HOST=chroma-server
      - PYTHONPATH=/app
    depends_on:
      - redis
    restart: unless-stopped

  # for local testing only
  chroma-server:
    image: chromadb/chroma:0.5.23
    ports:
      - "8000:8000"
    restart: unless-stopped
