name: kollektiv-external-deps
services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
