from enum import Enum
from typing import Any, ClassVar, TypedDict
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from src.models.base_models import BaseDbModel


# Base LLM models
class StandardEventType(str, Enum):
    """Standardized event types mapped from Anthropic events."""

    # Regular message events
    MESSAGE_START = "message_start"
    TEXT_TOKEN = "text_event"  # maps from text event
    MESSAGE_STOP = "message_stop"  # maps from message_stop

    # Tool-related events
    TOOL_START = "tool_start"  # maps from content_block_start with tool_use
    TOOL_RESULT = "tool_result"  # when tool execution completes

    # Error events
    ERROR = "error"  # any error during processing


class MessageContent(TypedDict):
    """Type definition for message content."""

    message_type: str = Field(
        ...,
        alias="type",
        description="Maps to Anthropic message types",
    )
    content: str = Field(..., description="Content of the llm message")
    tool_use_id: str | None = Field(None, description="ID of the tool use if relevant")


class StandardEvent(BaseModel):
    """Standard event structure for internal use."""

    event_type: StandardEventType
    content: str | dict[str, Any] = Field(description="Event content - text for tokens, structured data for tools")
    tool_info: dict[str, Any] | None = Field(None, description="Tool-specific information when relevant")
    message_id: UUID | None = Field(None, description="ID of the message this event belongs to")


class Role(str, Enum):
    """Roles in the conversation."""

    ASSISTANT = "assistant"
    USER = "user"


class ConversationMessage(BaseDbModel):
    """A message in a conversation between a user and an LLM."""

    message_id: UUID = Field(default_factory=uuid4, description="UUID of a message generated by the application.")
    conversation_id: UUID | None = Field(
        None,
        description="FK reference to a conversation. Can be empty? How can it not be empty? We should create conversation before saving a message?",
    )
    role: Role = Field(..., description="Role of the message sender")
    content: MessageContent = Field(..., description="Structured content of the message")
    text: str = Field(..., description="Text of the message, provides easy access to the UI.")

    _db_config: ClassVar[dict] = {"schema": "chat", "table": "conversation_messages", "primary_key": "message_id"}
    """Domain model for conversations."""


# TODO: to refactor
class ConversationMessage:
    """
    Represent a conversation message with an ID, role, and content.

    Args:
        role (str): The role of the message sender (e.g., 'user', 'system').
        content (Union[str, list[MessageContent]]): The content of the message.
    """

    def __init__(self, role: str, content: str | list[MessageContent]) -> None:
        self.id: str = str(uuid.uuid4())
        self.role: str = role
        self.content: str | list[MessageContent] = content

    def to_dict(self, include_id: bool = False) -> dict[str, Any]:
        """Convert the message object to a dictionary."""
        message_dict: dict[str, Any] = {"role": self.role, "content": self.content}
        if include_id:
            message_dict["id"] = self.id
        return message_dict


class ConversationRecency(str, Enum):
    """A domain model for a group of conversations ordered by time."""

    RECENT = "recent"
    LAST_THIRTY_DAYS = "last_thirty_days"
    OLDER = "older"


class Conversation(BaseDbModel):
    """Domain model for a conversation."""

    conversation_id: UUID = Field(default_factory=uuid4, description="UUID of the conversation")
    user_id: UUID = Field(..., description="FK reference to UUID of the user")
    title: str = Field(..., description="Title of the conversation")
    data_sources: list[UUID] = Field(
        default=...,
        description="FK references to UUIDs of the data sources last active for the conversation",
    )

    _db_config: ClassVar[dict] = {"schema": "chat", "table": "conversations", "primary_key": "conversation_id"}


class Conversations(BaseModel):
    """A domain model for a list of conversations that a user has."""

    user_id: UUID = Field(..., description="FK reference to UUID of the user")
