name: Docker Build and Push

on:
  push:
    paths:
      - "scripts/docker/Dockerfile"
      - "src/**"
      - "pyproject.toml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scripts/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kollektiv-rq:latest
            ghcr.io/${{ github.repository_owner }}/kollektiv-rq:${{ github.sha }}
