name: Docker Build and Push

on:
  push:
    paths:
      - ".github/workflows/docker-deploy.yml"
      - "scripts/docker/Dockerfile"
      - "scripts/docker/compose.yaml"
      - "src/**"
      - "pyproject.toml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: scripts/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kollektiv-rq:latest
            ghcr.io/${{ github.repository_owner }}/kollektiv-rq:${{ steps.get_tag.outputs.LATEST_TAG }}

      - name: Trigger Railway redeploy
        run: |
          echo "Triggering deployment for project: ${RAILWAY_PROJECT_ID}"
          echo "Service ID: ${RAILWAY_SERVICE_ID}"
          response=$(curl -X POST \
            -H "Authorization: Bearer ${RAILWAY_TOKEN}" \
            -H "Content-Type: application/json" \
            -v \
            "https://backboard.railway.app/api/projects/${RAILWAY_PROJECT_ID}/services/${RAILWAY_SERVICE_ID}/deployments")
          echo "Response: $response"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
