name: Pull Request Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_pr_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate PR Description
        run: |
          echo "## Changes in this PR:" > pr_body.md
          echo "" >> pr_body.md
          git log --format="- %s" origin/${{ github.base_ref }}..origin/${{ github.head_ref }} >> pr_body.md
      - name: Update PR
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          body-path: "pr_body.md"
          body-if-empty: true
